service: alpha-lambda-reference

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  
custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - serverless/**

functions: ${file(./serverless/functions.yml)}