dynamodbReader:
  Effect: Allow
  Action:
    - dynamodb:BatchGetItem
    - dynamodb:GetItem
    - dynamodb:Query
    - dynamodb:Scan
  Resource:
    Fn::ImportValue: ${self:custom.namespace}-table-arn

dynamodbWriter:
  Effect: Allow
  Action:
    - dynamodb:UpdateItem
  Resource:
    Fn::ImportValue: ${self:custom.namespace}-table-arn

sqsReader:
  Effect: Allow
  Action:
    - sqs:DeleteM*
    - sqs:GetQueueAttributes
    - sqs:ReceiveMessage
  Resource:
    - Fn::ImportValue: ${self:custom.namespace}-send-notification-tasks-queue-arn
    - Fn::ImportValue: ${self:custom.namespace}-update-vote-count-tasks-queue-arn

sqsWriter:
  Effect: Allow
  Action:
    - sqs:SendM*
  Resource:
    - Fn::ImportValue: ${self:custom.namespace}-send-notification-tasks-queue-arn
    - Fn::ImportValue: ${self:custom.namespace}-update-vote-count-tasks-queue-arn
    - Fn::ImportValue: ${self:custom.namespace}-stream-dlq-arn

xRayWriter:
  Effect: Allow
  Action:
    - xray:PutTraceSegments
    - xray:PutTelemetryRecords
  Resource: '*'
